apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: 'https://github.com/seu-usuario/seu-repositorio.git'
    targetRevision: HEAD
    path: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
